### ISSUE TITLE
간헐적으로 게임이 종료되는 현상

### ISSUE THREAD

**Issue by SpiceSoy** [SpiceSoy/KPU-2DGP-RhythmCrush#27]
사실상 거의 완성인 지금 가장 큰 문제.

간헐적으로 게임이 종료되는 현상.

게임 플레이하며 WAV 확장자로 된 음악 플레이시 간헐적으로 게임이 종료됨

파이참 디버그 콘솔에는 SDL_TEXT 에서 surface 를 리소스 해제 (Free) 할 때 엑세스 위반이 뜸

보통 플레이어 인풋과 함께 발생하는 편이나 실제 스택에서 터지는 코드 확인해보면 대부분 배속 UI 에서 튕기는 것을 볼 수 있음.

일단 기존에 있던 두 곡 맥스버닝하고 카메리아 곡은 해당 현상이 안 일어나는 것으로 보이고

이 증상이 일어나는 노래들이 mp3 파일로 넣으면 재생이 안되는 파일들이었음이 특징적

오디오 버퍼를 512에서 1024로 바꾸니 증상 빈도가 줄은 것으로 보아 음악파일과 관련이 있다고 생각됨.

일단 근본적인 버그 수정이 목표이나 그것이 힘들면 전문적인 오디오 컨버터로 다른 포맷으로 컨버팅 하는 등의 해결이 필요하여 보임.

**Comment by SpiceSoy** [comment]
1. 노래 재생을 안하면 안팅귐

**Comment by SpiceSoy** [comment]
2. 노래 재생 하면 칼같이 팅김

**Comment by SpiceSoy** [comment]
Traceback (most recent call last):
  File "C:/Users/Soy/OneDrive/1902/KPU-2DGP-RhythmCrush/run.py", line 3, in <module>
    from RhythmCrush import main
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\main.py", line 7, in <module>
    game.loop()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\framework.py", line 36, in loop
    self.draw()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\framework.py", line 44, in draw
    self.scene_stack[-1].draw()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\game_scene\game_map.py", line 128, in draw
    super().draw()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\game_scene\base_scene.py", line 48, in draw
    self.game_world.draw()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\game_object\game_world.py", line 45, in draw
    o.draw()
  File "C:\Users\Soy\OneDrive\1902\KPU-2DGP-RhythmCrush\RhythmCrush\ui\ui_text.py", line 32, in draw
    self.font.draw(self.position[0], self.position[1], self.text + " ", self.color)
  File "C:\Program Files\Python37\lib\site-packages\pico2d\pico2d.py", line 360, in draw
    SDL_FreeSurface(surface)

**Comment by SpiceSoy** [comment]
실제 팅기는 방법은 위의 폰트에서 FreeSurface 할 때 팅기던가
아니면 그냥 0x0000C5 였나의 오류문구 남기고 바로 꺼짐

**Comment by SpiceSoy** [comment]
맨처음에는 WAV 파일 쓰는 곡만 팅기는 줄 알았더니 꼭 그렇지는 않은 것 같음

**Comment by SpiceSoy** [comment]
원본 mp3 : 재생 안됨
mp3 -> wav : 재생 되나 메모리 엑세스 위반 뜸
mp3 -> wav- > mp3 : 재생 잘 됨 아직까지 안팅긴듯

**Comment by SpiceSoy** [comment]
mp3 -> wav- > mp3 : wake업은 이것도 안됨
mp3-> wav -> ogg: wake업은 이거는 됨

**Comment by SpiceSoy** [comment]
일단 모든 노래에서 wav 뻈음

실제로 팅기는 확률 매우 감소.
